config/routes.rb
Rails.application.routes.draw do
  require("sidekiq/web")
  root 'pages#index'
  get 'users/signup',to: "users#new",as: 'new_signup'
  post 'users/signup',to: "users#create",as: 'signup'
  get "users/login",to: "sessions#new",as: 'login'
  post "users/login",to: "sessions#create",as: 'create_session'
  delete "users/logout",to: "sessions#destroy",as: 'destroy_session'
  get "users/:id",to: "users#show",as: 'user'
  resources :projects do 
    resources :bids,only: [:new,:create]
  end

    mount Sidekiq::Web => '/sidekiq'
  post "/deleteAllExpiredBids",to: "projects#destroy_expired_bids",as: 'delete_all_expired_bids'

  match '*path', to: 'errors#not_found', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :project
  validates :amount,presence: true
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord 
  belongs_to :user 
  validates :title, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :url, presence: true, format: { with: /\A#{URI::regexp(['http', 'https'])}\z/ }
  validates :bid_time, presence: true
  validate :bid_time_cannot_be_in_the_past
  has_many :bids, dependent: :destroy
  before_validation :set_default_bid_time, on: :create

  def add_bid(bid)
    if self.bids.empty?
      self.bid = bid.amount
    else 
      if self.bids.last.amount < bid.amount
        self.bid = bid.amount
      end
    end
  end

  def validate_bid_time 
    self.bid_time >= DateTime.now
  end

  def bid_time_cannot_be_in_the_past
    if bid_time.present? && bid_time < Time.now
      errors.add(:bid_time, "cannot be in the past")
    end
  end

  def set_default_bid_time
    self.bid_time ||= Time.now + 12.hours
  end

  def display_datetime 
    self.bid_time.strftime("%b %d, %Y at %l:%M %p")
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password 
    validates :phone, phone: true 
    validates :password, presence: true, confirmation: true, length: { minimum: 6 }
    validates :password_confirmation, presence: true
    has_many :projects , dependent: :destroy
    enum role: [:buyer,:seller,:admin]
    has_many :bids, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user,:login,:logout,:require_user!,:check_user_bid 


    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def login(user)
        session[:user_id] = user.id
    end

    def logout 
        session[:user_id] = nil
    end

    def require_user!
        if !current_user
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end

    def check_user_bid(project) 
        if current_user
            if current_user && !current_user.bids.empty?
                current_user.bids.exists?(project_id: project.id)
            else
                false
            end
        end
    end

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController 
    before_action :set_project, only: [:new, :create]
    before_action :require_user!, only: [:new, :create]

    def new 
        @bid = Bid.new
    end

    def create 
        @bid = @project.bids.build(bid_params)
        @bid.user_id = current_user.id 
        @project.add_bid(@bid)
        respond_to do |format|
        if @bid.save
           format.turbo_stream {
            render turbo_stream: turbo_stream.replace("bid-form", partial: "bids/success")
           }
           format.html { redirect_to project_path(@project) }
        else
            format.html { render :new, status: :unprocessable_entity }
        end
    end
    end



    private 

        def set_project 
            @project = Project.find(params[:project_id])
        end

        def bid_params
            params.require(:bid).permit(:amount)
        end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  
  def not_found
    render file: Rails.public_path.join('404.html'), status: :not_found, layout: false
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :restrict_user!
  
  def index
  end



  private 

    def restrict_user!
      if current_user
        redirect_to projects_path
      end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController 
    before_action :require_admin!,only: [:destroy_expired_bids]
    before_action :require_user!, except: %i[index show] 
    before_action :set_project , only: [:show,:destroy]
    before_action :check_user_role, only: [:new, :create]

    def index
        @projects = Project.all 
    end 

    def show 
        @bids = @project.bids.order("amount DESC")
    end

    def new 
        @project = Project.new 
    end

    def create 
        @project = Project.new(project_params)
        @project.user = current_user
        if @project.save 
            flash[:success] = "Project was successfully created"
            redirect_to project_path(@project)
        else
            flash.now[:danger] = @project.errors.full_messages.to_sentence
            render 'new', status: :unprocessable_entity
        end
    end

    def destroy_expired_bids
        projects = Project.where('bid_time <= ?', DateTime.now)
        project_ids = projects.pluck(:id)
        BidsJob.perform_at(1.minute.from_now,project_ids)
    end

    def destroy 
        @project.destroy
        flash[:success] = "Project was successfully deleted"
        redirect_to projects_path
    end



    private 

        def project_params
            params.require(:project).permit(:title, :description, :url,:bid_time)
        end

        def set_project
            @project = Project.find(params[:id])
        end

        def check_user_role
            if !current_user.seller?
                flash[:danger] = "You are not authorized to perform that action"
                redirect_to root_path
            end
        end

        def require_admin!
            if !current_user.admin?
                flash[:danger] = "You are not authorized to perform that action"
                redirect_to root_path
            end
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :check_user, only: [:new, :create]

    def new 

    end

    def create 
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password]) 
            login(@user)
            flash[:success] = "You have successfully logged in"
            redirect_to projects_path
        else 
            flash[:danger] = "Invalid email/password"
            redirect_to login_path
        end
    end

    def destroy 
        logout
        flash.now[:notice] = "You have successfully logged out"
        redirect_to root_path
    end

    private 
    def check_user
        if current_user
            flash.now[:notice] = "You are already logged in"
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new 
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to root_path
            flash[:success] = "User created successfully"
        else 
            flash.now[:danger] = @user.errors.full_messages
            render :new
        end
    end

    def destroy 
        @user = User.find(params[:id])
        logout
        @user.destroy
        redirect_to root_path, notice: "User has been deleted"
    end

    private 

        def user_params
            params.require(:user).permit(:username,:email,:phone,:password,:password_confirmation,:role)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bids/_success.html.erb
<%= turbo_frame_tag "bid-form" do %>
  <div class="flex items-center p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
    <svg class="flex-shrink-0 inline w-4 h-4 mr-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <div>
      <span class="font-medium">Success!</span> Your Bid has been submitted. You'll receive a confirmation email shortly.
    </div>
  </div>
<% end %>

app/views/bids/new.html.erb
<%= turbo_frame_tag "bid-form" do %>
  <%= form_with(model: [@project,@bid],html: {class: "flex flex-row gap-2"}) do |f| %>
    <%= f.text_field :amount, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2",placeholder: "Enter Bid Amount in USD($)" %>
    <%= f.submit "Submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"  %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-white shadow dark:bg-gray-900 py-4 mt-auto">
  <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between pt-3">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="https://flowbite.com/" class="hover:underline">Flowbite™</a>. All Rights Reserved.</span>
    <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">About</a>
      </li>
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
      </li>
      <li>
        <a href="#" class="mr-4 hover:underline md:mr-6">Licensing</a>
      </li>
      <li>
        <a href="#" class="hover:underline">Contact</a>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 left-0 border-b border-gray-200 dark:border-gray-600">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="<%= root_path %>" class="flex items-center">
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">ProjectBidding</span>
    </a>
    <div class="flex md:order-2">
      <% if !current_user %>
        <%= link_to "Get started",login_path,class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded text-sm px-4 py-2 text-center mr-3 md:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
      <% else %>
        <%= link_to "Logout",destroy_session_path,data: {turbo_method: "delete"},class: "
        text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded text-sm px-4 py-2 text-center mr-3 md:mr-0 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800
        " %>
      <% end %>
      <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
      </button>
    </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
      <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <% if current_user && current_user.seller? %>
          <li>
            <%= link_to "Add Project",new_project_path,class: "block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" %>
          </li>
        <% end %>
        <li>
          <%= link_to "Projects",projects_path,class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
        </li>
        <% if current_user %>
          <li>
            <a href="<%= user_path(current_user) %>" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"><%= current_user.username if current_user%></a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/pages/index.html.erb
<section class="bg-white dark:bg-gray-900 h-auto py-40">
  <div class="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
    <div class="mr-auto place-self-center lg:col-span-7">
      <h1 class="max-w-2xl mb-4 text-3xl font-extrabold tracking-tight leading-none md:text-5xl xl:text-6xl dark:text-white">Rails Creations: Where Innovation Meets Opportunity!</h1>
      <p class="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">Unlock a world of innovation and global sales opportunities with Rails Creations – Where creativity knows no bounds!</p>
      <%= link_to new_signup_path do %>
        <span class="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900 cursor-pointer">
          Get started
          <svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </span>
      <% end %>
      <%= link_to login_path do %>
        <span class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
          Login 
        </span>
      <% end %>
    </div>
    <div class="hidden lg:mt-0 lg:col-span-5 lg:flex">
      <%= image_tag("hero-3-extra.png",alt: "Mockup") %>
    </div>
  </div>
</section>

app/views/projects/_bid.html.erb
<div class="flex flex-row justify-between items-center mt-3">
  <span class="dark:text-white text-xl"><%= bid.user.username %></span>
  <span class="dark:text-white">Bid Amount : <span class="bg-green-100 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300"> <%= bid.amount %>$ </span></span>
</div>

app/views/projects/index.html.erb
<div class="mt-32">
  <h1 class="text-4xl font-bold text-white text-center">Check out some projects build by our mentors</h1>
  <p class="text-white text-center w-[60%] mx-auto mt-5 text-sm">
    Discover the magic of collaboration as you explore a medley of projects, crafted by our skilled mentors, united by their vision for extraordinary creations.
  </p>
</div>
<div class="flex justify-center items-center my-32 gap-x-5">
  <% @projects.each_with_index do |project,index|  %>
    <div class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
      <a href="<%= project_path(project) %>" class="text-white text-3xl flex justify-center mb-10 border-b border-slate-300">
        Project-<%= index+1 %>
      </a>
      <div class="px-5 pb-5">
        <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white"><%= project.title %></h5>
        <p class="mt-2 text-sm text-gray-500 dark:text-gray-400"><%= (project.description).truncate(100) %></p>
        <div class="flex items-center justify-between">
          <span class="text-3xl font-bold text-gray-900 dark:text-white"><%= project.bid.amount if project.bid %></span>
          <a href="<%= project_path(project) %>" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 mt-2">Show</a>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% if current_user && current_user.admin? %>
  <%= button_to "Delete Expired Bids",delete_all_expired_bids_path,remote: true,method: :post,class:"bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring focus:border-blue-300" %>
<% end%>

app/views/projects/show.html.erb
<div class="flex justify-center items-center mt-32 flex-col">
  <div class="bg-slate-800">
    <% if current_user && current_user.id == @project.user_id || @project.user.admin? %>
      <%= link_to "Remove Project From Bidding?", project_path(@project),data: {turbo_method: "delete",turbo_confirm: "Are you sure you want to remove the project from bidding, once done you can't undo it...."}, class: "bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:border-red-300 flex justify-center items-center mb-5" %>
    <% end %>
    <h1 class="text-3xl dark:text-white font-bold"><%= @project.title %></h1>
    <div class="flex flex-row justify-between items-center mt-3">
      <small class="dark:text-white">Created by <%= @project.user.username %></small>
      <small class="dark:text-white">Bid will expire on <span class="bg-blue-100 text-blue-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300"><%= @project.display_datetime if @project.bid_time %></span>
      </small>
    </div>
    <div class="mt-12 flex flex-col">
      <span class="dark:text-white">Checkout Project here: <br>
        <a href="<%= @project.url %>" class="text-blue-500 dark:text-blue-400 underline hover:cursor-pointer" target="_blank"><%= @project.url %></a></span>
      <span class="dark:text-white font-medium w-[600px] mx-auto pb-24 pt-10">
        <%= @project.description %>
      </span>
    </div>
    <div class="mt-12 mb-12">
      <% @bids.each do |bid| %>
        <%= render 'projects/bid', bid: bid %>
      <% end %>
    </div>
  </div>
  <% if current_user && !check_user_bid(@project) && current_user.buyer? && @project.bid_time > DateTime.now %>
    <div class="pt-12 pb-32 w-[600px] ">
      <%= turbo_frame_tag "bid-form" do %>
        <%= link_to "Bid Now",new_project_bid_path(@project),class:"bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring focus:border-blue-300" %>
      <% end %>
    </div>
  <% end %>
  <% if @project.bid_time < DateTime.now %>
    <marquee class="text-red-500" behavior="scroll" direction="left">Bid has expired</marquee>
  <% end %>
  <% if @project.bid_time < DateTime.now %>
    <span>Bid sold to : </span>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for user,url: signup_path,html: {data:{turbo: false}} do |u| %>
  <div class="relative z-0 w-full mb-6 group">
    <%= u.text_field :username,id: "username",class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer",placeholder: "",required: true %>
    <label for="username" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Username</label>
  </div>
  <div class="relative z-0 w-full mb-6 group">
    <%= u.text_field :email,id: "email",class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer",placeholder: "",required: true %>
    <label for="email" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Email</label>
  </div>
  <div class="grid md:grid-cols-2 md:gap-6">
    <div class="relative z-0 w-full mb-6 group">
      <%= u.password_field :password,id: "password",class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer",placeholder: "",required: true %>
      <label for="password" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Password</label>
    </div>
    <div class="relative z-0 w-full mb-6 group">
      <%= u.password_field :password_confirmation,id: "password_confirmation",class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer",placeholder: "",required: true %>
      <label for="password_confirmation" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Confirm password</label>
    </div>
  </div>
  <div class="relative z-0 w-full mb-6 group">
    <%= u.text_field :phone,id: "phone",class: "block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer",placeholder: "",required: true %>
    <label for="phone" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Phone number</label>
  </div>
  <div class="grid md:grid-cols-2 md:gap-6 mb-5">
    <div class="flex items-center">
      <%= u.radio_button :role,"buyer",id: "buyer",class: "w-4 h-4 border-gray-300 focus:ring-2 focus:ring-blue-300 dark:focus:ring-blue-600 dark:focus:bg-blue-600 dark:bg-gray-700 dark:border-gray-600" %>
      <label for="buyer" class="block ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">
        Buyer
      </label>
    </div>
    <div class="flex items-center">
      <%= u.radio_button :role,"seller",id: "seller",class: "w-4 h-4 border-gray-300 focus:ring-2 focus:ring-blue-300 dark:focus:ring-blue-600 dark:focus:bg-blue-600 dark:bg-gray-700 dark:border-gray-600" %>
      <label for="seller" class="block ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">
        Seller 
      </label>
    </div>
  </div>
  <%= u.submit "Submit",class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 cursor-pointer" %>
<% end %>
<span class="text-white mt-4 text-center pb-5 text-sm">
  Already have an account <%= link_to "Sign in",login_path,method: :get,class: "text-blue-600 hover:underline" %>
</span>

app/views/users/new.html.erb
<div class="flex justify-center items-center flex-col pt-32 bg-slate-800">
  <h1 class="text-4xl font-bold text-slate-300 mb-12">Register Yourself</h1>
  <%= render 'form',user: @user %>
</div>